### PR TITLE
Gort 69

### PR DESCRIPTION
**Pull request by Jatanasio**

### CODE REVIEW

**Review by Michael0131 — CHANGES_REQUESTED** [review]
Bite does not register, only animation is shown. Need to maipulate enemy class to where damage on player is False if player is doing "bite". Also pause does not seem to do anything.

**Review by Michael0131 — APPROVED** [review]
works

**Review by Michael0131 — APPROVED** [review]
epic, maybe change spawn after full death. looks good tho

**Review by despan5 — APPROVED** [review]
gort

**Pull request merged**
