### PR TITLE
Database first steps...

### PR DESCRIPTION
**Pull request by ThomaseLucas**
added an input box for users, and made the input get put into the database along with their current score. Hopefully there aren't any conflicts

### CODE REVIEW

**Review by despan5 — DISMISSED** [review]
diggity

**Comment by Jatanasio** [comment]
yeehaw

**Review by Jatanasio — DISMISSED** [review]

**Review by Jatanasio — APPROVED** [review]
f it we ball

**Review by despan5 — APPROVED** [review]
yuh

**Pull request merged**
